<?xml version="1.0"?>
<!DOCTYPE DB_USERS [
<!ELEMENT DB_USERS (USER)*>
<!ELEMENT USER (NAME, PASSWORD, PRIVILEGE)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT PASSWORD (#PCDATA)>
<!ELEMENT PRIVILEGE (#PCDATA)>
<!ELEMENT STATUS (#PCDATA)>
]>
<DB_USERS>
<USER>
<NAME>admin</NAME>
<PASSWORD>1f40fc92da241694750979ee6cf582f2d5d7d28e18335de05abc54d0560e0f5302860c652bf08d560252aa5e74210546f369fbbbce8c12cfc7957b2652fe9a75</PASSWORD>
<PRIVILEGE>AdminPrivilege</PRIVILEGE>
<STATUS>READY</STATUS>
</USER>
<USER>
<NAME>user</NAME>
<PASSWORD>1f40fc92da241694750979ee6cf582f2d5d7d28e18335de05abc54d0560e0f5302860c652bf08d560252aa5e74210546f369fbbbce8c12cfc7957b2652fe9a75</PASSWORD>
<PRIVILEGE>NormalUser</PRIVILEGE>
<STATUS>READY</STATUS>
</USER>
</DB_USERS>
